name: Run gradlew test

on:
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  build_test_and_coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run gradlew test
        run: ./gradlew test --warning-mode=all

      - name: Upload test coverage to Codecov.io
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
          verbose: true
          flags: ${{ github.ref == 'refs/pull/develop' && 'integration' || 'unittests' }}
